# VictorsWallet - makefile
VictorsWallet: 
		javac *.java && javac Wallet/*.java && javac Wallet/Parsers/*.java && javac Wallet/Cards/*.java
	
clean:
	rm *.java
	rm Wallet/*.java
	rm Wallet/Parsers/*.java
	rm Wallet/Cards/*.java
